# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Admin.create([
  { :email => "beornf@gmail.com", :password => "temp1234", :password_confirmation => "temp1234", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1" }
], :without_protection => true )
