# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Feed.create([
  { :active => false, :name => "Stack Overflow", :url => "http://careers.stackoverflow.com/jobs/feed", :newer => true, :rss => true },
  { :active => false, :name => "37signals", :url => "http://jobs.37signals.com/jobs.rss", :newer => true, :rss => true },
  { :active => false, :name => "Ruby Now", :url => "http://feeds.feedburner.com/jobsrubynow?format=xml", :newer => false, :rss => true },
  { :active => false, :name => "GitHub Jobs", :url => "https://jobs.github.com/positions.atom", :newer => true, :rss => true },
  { :active => false, :name => "Crunchboard Jobs", :url => "http://feeds.feedburner.com/CrunchboardJobs?format=xml", :newer => true, :rss => true },
  { :active => false, :name => "Hacker News Jobs", :url => "http://hnhiring.com/", :newer => true, :rss => false },
  { :active => false, :name => "Authentic Jobs", :url => "http://www.authenticjobs.com/rss/custom.php?terms=&type=1,3", :newer => false, :rss => true },
  { :active => false, :name => "Smashing Jobs", :url => "http://jobs.smashingmagazine.com/rss/all/all", :newer => false, :rss => true }
])


