defaults: &defaults
  title: Tech Savvy Jobs
  description: Endless opportunities for web and creative professionals
  meta_author: Tech Savvy Jobs Pty Ltd
  meta_keywords: "Tech, Savvy, Jobs, IT"
  meta_viewport: "width=device-width, initial-scale=1, maximum-scale=1"
  shim_url: http://html5shim.googlecode.com/svn/trunk/html5.js

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
